(ns tools.registry
  "Component & icon registry — powers `bb list-components`,
   `bb list-icons` and `bb gen-docs` (docs/components.md)."
  (:require [babashka.fs :as fs]
            [clojure.string :as str]
            [ui.icon :as icon]))

;; ── Components ──────────────────────────────────────────────────────

(defn- ns-doc
  "First line of the ns docstring, if any."
  [src]
  (when-let [[_ doc] (re-find #"(?s)\(ns\s+[^\s)]+\s+\"((?:[^\"\\]|\\.)*)\"" src)]
    (-> doc
        (str/replace "\\\"" "\"")
        str/split-lines
        first
        str/trim)))

(defn- public-fns
  "Names of public defns (excludes defn-)."
  [src]
  (->> (re-seq #"(?m)^\(defn (\S+)" src)
       (map second)
       distinct
       vec))

(defn components
  "All ui/*.cljc components: {:name :ns :doc :fns}."
  []
  (->> (fs/glob "src/ui" "*.cljc")
       (map str)
       sort
       (map (fn [f]
              (let [src (slurp f)]
                {:name (str/replace (fs/file-name f) #"\.cljc$" "")
                 :ns   (second (re-find #"\(ns\s+([^\s)]+)" src))
                 :doc  (ns-doc src)
                 :fns  (public-fns src)})))))

;; ── Icons ───────────────────────────────────────────────────────────

(defn icons
  "All icon names (sorted strings) and the set with dedicated filled paths."
  []
  {:names  (sort (map name (keys icon/icon-paths)))
   :filled (set (map name (keys icon/filled-icon-paths)))})

;; ── Printing ────────────────────────────────────────────────────────

(defn print-components! []
  (let [comps (components)]
    (println (count comps) "components in src/ui/*.cljc\n")
    (doseq [{:keys [name ns doc fns]} comps]
      (println (format "%-18s %-22s %s" name ns (or doc "")))
      (when (seq fns)
        (println (str "                   " (str/join ", " fns)))))))

(defn print-icons! []
  (let [{:keys [names filled]} (icons)]
    (println (count names) "icons —" (count filled) "with dedicated filled variants (*)\n")
    (doseq [row (partition-all 4 names)]
      (println (str/join "  " (map #(format "%-22s" (str % (when (filled %) " *"))) row))))))

;; ── Docs page ───────────────────────────────────────────────────────

(defn- md-code-list [xs]
  (str/join ", " (map #(str "`" % "`") xs)))

(defn gen-docs!
  "Write docs/components.md — generated listing of components + icons."
  []
  (let [comps (components)
        {:keys [names filled]} (icons)
        md (str
            "# Components & Icons\n\n"
            "> Generated by `bb gen-docs` — do not edit by hand.\n"
            "> See `AGENTS.md` for conventions, per-target pitfalls, and how to\n"
            "> add new components and icons.\n\n"
            "## Components (" (count comps) ")\n\n"
            "| Component | Namespace | Description | Public API |\n"
            "|-----------|-----------|-------------|------------|\n"
            (str/join
             (for [{:keys [name ns doc fns]} comps]
               (str "| " name " | `" ns "` | " (or doc "") " | "
                    (md-code-list fns) " |\n")))
            "\n## Icons (" (count names) ")\n\n"
            "Lucide-compatible inline SVG icons — see `AGENTS.md` § Icons for\n"
            "usage and how to add new ones.\n\n"
            (md-code-list names) "\n\n"
            "Icons with dedicated filled path data (`:filled true`):\n\n"
            (md-code-list (sort filled)) "\n")]
    (fs/create-dirs "docs")
    (spit "docs/components.md" md)
    (println "Generated docs/components.md —"
             (count comps) "components," (count names) "icons")))
